name: project_template
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.21.0+1
  get: ^4.3.0
  get_storage: ^2.0.2
  modal_bottom_sheet: ^2.0.0
  fluttertoast: ^8.0.4
  dio: ^4.0.0
  dartz: ^0.10.0-nullsafety.2
  flutter_spinkit: ^5.0.0
  cached_network_image: ^3.1.0
  flutter_native_splash: ^1.2.1
  flutter_launcher_icons: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  change_app_package_name: ^1.0.0
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: PulpDisplay
      fonts:
        - asset: assets/fonts/PulpDisplay-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/PulpDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/PulpDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/PulpDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/PulpDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PulpDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/PulpDisplay-ExtraBold.ttf
          weight: 900

